=== xkalv011/xkalv011-prace/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified">
	<xs:element name="knihovna">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="konfigurace" minOccurs="1" maxOccurs="1">
				<xs:complexType>
				<xs:sequence>
					<xs:element name="lang" type="xs:string" default="cs"/>
					<xs:element name="coding" type="xs:string"  fixed="UTF-8"/>
					<xs:element name="aplication_version" type="xs:string"/>
					<xs:element name="background_color" type="xs:string" default="#FFF"/>
					<xs:element name="font_color" type="xs:string" default="#000"/>
					<xs:element name="site_name" type="xs:string"/>
					<xs:element name="aplication_name" type="xs:string"/>
					<xs:element name="meta" type="xs:boolean"/>
					<xs:element name="description" type="xs:boolean"/>
					<xs:element name="pouzivani_cookie" type="xs:boolean"/>
					<xs:element name="show_reklamy" type="xs:boolean"/>
					<xs:element name="app_image" type="xs:string"/>
					<xs:element name="stylesheet">
						<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="type" type="xs:string"/>
							</xs:extension>
						</xs:simpleContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="screen_resolution" minOccurs="1" maxOccurs="1">
						<xs:complexType>
						<xs:sequence>
							<xs:element name="responsive" type="xs:boolean"/>
							<xs:element name="vyska" type="xs:integer"/>
							<xs:element name="sirka" type="xs:integer"/>						
						</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="autor_aplikace" type="xs:string"/>
					<xs:element name="kontakt_mail" type="xs:string"/>
					<xs:element name="zdroj_aplikace" type="xs:string"/>
					<xs:element name="socialni_site" type="xs:string"/>
					<xs:element name="server_hosting" type="xs:string"/>
				</xs:sequence>
				</xs:complexType>
			</xs:element><!--Konec konfigurace-->
			
			<xs:element name="kniha" maxOccurs="unbounded">
				<xs:complexType>
				<xs:sequence>
					<xs:element name="nazev_knihy">
						<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="lang" type="xs:string" use="required"/>
							</xs:extension>
						</xs:simpleContent>							
						</xs:complexType>
					</xs:element>					
					<xs:element name="autor" minOccurs="1">
						<xs:complexType>
						<xs:sequence>
							<xs:element name="jmeno" type="xs:string"/>
							<xs:element name="prijmeni" type="xs:string"/>
						</xs:sequence>
							<xs:attribute name="pohlavi" type="xs:string"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="klicova_slova" type="xs:string"/>
					<xs:element name="vydavatelstvi" type="xs:string"/>
					<xs:element name="zanr" type="xs:string"/>
					<xs:element name="rok_vydani" type="xs:date"/>
					<xs:element name="jazyk_knihy" type="xs:string"/>
					<xs:element name="kod_knihy" type="xs:integer"/>
					<xs:element name="nor_kod">
						<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="ISBN" type="xs:boolean"/>
							</xs:extension>
						</xs:simpleContent>								
						</xs:complexType>
					</xs:element>
					<xs:element name="pocet_stran" type="xs:integer"/>
					<xs:element name="stav_knihy" type="xs:string"/>					
					<xs:element name="stav" type="xs:string"/>
					<xs:element name="pocet_kusu" type="xs:integer"/>
					<xs:element name="cena">
						<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:integer">
								<xs:attribute name="mena" type="xs:string"/>
								<xs:attribute name="cena_s_DPH" type="xs:boolean"/>
							</xs:extension>
						</xs:simpleContent>							
						</xs:complexType>
					</xs:element>
					<xs:element name="popis_knihy" type="xs:string"/>
					<xs:element name="rozsireni">
						<xs:complexType>
						<xs:sequence>
							<xs:element name="hodnoceni" type="xs:integer"/>
							<xs:element name="pocet_recenzi" type="xs:integer"/>
							<xs:element name="komentare" type="xs:integer"/>
							<xs:element name="zajimavosti" type="xs:string"/>
						</xs:sequence>
							<xs:attribute name="show" type="xs:boolean"/>
						</xs:complexType>
					</xs:element>					
					<xs:element name="nahled_knihy" minOccurs="1">
						<xs:complexType>
						<xs:sequence>
							<xs:element name="odkaz_na_soubor" type="xs:string"/>
							<xs:element name="velikost" minOccurs="1" maxOccurs="1">
							<xs:complexType>
							<xs:sequence>
								<xs:element name="vyskaNahled" type="xs:integer"/>
								<xs:element name="sirkaNahled" type="xs:integer"/>
							</xs:sequence>
							</xs:complexType>
							</xs:element>
							<xs:element name="zvetseni" type="xs:boolean"/>
							<xs:element name="popis" type="xs:string"/>
						</xs:sequence>
							<xs:attribute name="nahledID" type="xs:positiveInteger" use="required"/>
							<xs:attribute name="format" type="xs:string"/>
						</xs:complexType>
					</xs:element>					
					<xs:element name="informace_o_zaznamu" minOccurs="1">
						<xs:complexType>
						<xs:sequence>
							<xs:element name="datum_pridani" type="xs:date"/>
							<xs:element name="posledni_zmena" type="xs:date"/>
							<xs:element name="autor_zaznamu" type="xs:string"/>
						</xs:sequence>
							<xs:attribute name="existence" type="xs:boolean"/>
						</xs:complexType>
					</xs:element>					
				</xs:sequence>
					<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
					<xs:attribute name="zeme_puvodu" type="xs:string"/>
					<xs:attribute name="druh" type="xs:string"/>
				</xs:complexType>
			</xs:element><!--konec elementu kniha-->
		</xs:sequence>
		</xs:complexType>
	</xs:element><!--konec elementu knihovna-->
	
<!--omezeni-->
	<xs:element name="lang">
		<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:enumeration value="cs"/>
			<xs:enumeration value="sk"/>
			<xs:enumeration value="en"/>
			<xs:enumeration value="de"/>
		</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="sirka">
      <xs:restriction base="xs:integer">
         <xs:enumeration value="640" />
         <xs:enumeration value="854" />
         <xs:enumeration value="1280" />
         <xs:enumeration value="1920" />
         <xs:enumeration value="2560" />
         <xs:enumeration value="3840" />
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="vyska">
      <xs:restriction base="xs:integer">
         <xs:enumeration value="360" />
         <xs:enumeration value="480" />
         <xs:enumeration value="720" />
         <xs:enumeration value="1080" />
         <xs:enumeration value="1440" />
         <xs:enumeration value="2160" />
      </xs:restriction>
   </xs:simpleType>
	<xs:element name="nazev_knihy">
		<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:minLength value="4"/>
			<xs:maxLength value="30"/>
		</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="stav">
		<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Na skladě"/>
			<xs:enumeration value="Na prodejně"/>
			<xs:enumeration value="Rezervováno"/>
		</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="pocet_kusu">
		<xs:simpleType>
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-9]"/>
		</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:attribute name="format">
		<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="img|png|pdf"/>
		</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:simpleType name="sirkaNahled">
      <xs:restriction base="xs:integer">
         <xs:enumeration value="100" />
         <xs:enumeration value="200" />
         <xs:enumeration value="300" />
         <xs:enumeration value="500" />
      </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="vyskaNahled">
      <xs:restriction base="xs:integer">
         <xs:enumeration value="80" />
         <xs:enumeration value="180" />
         <xs:enumeration value="280" />
         <xs:enumeration value="480" />
      </xs:restriction>
   </xs:simpleType>
</xs:schema>

=== xkalv011/xkalv011-prace/data.xml
<?xml version="1.0" encoding="UTF-8"?> 
<knihovna xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<konfigurace>
		<lang>cs</lang>
		<coding>UTF-8</coding>
		<aplication_version>1.0</aplication_version>
		<background_color>#FFF</background_color>
		<font_color>#000</font_color>
		<site_name>Knižní mánie</site_name>
		<aplication_name>Knižní mánie</aplication_name>
		<meta>true</meta>
		<description>true</description>
		<pouzivani_cookie>false</pouzivani_cookie>
		<show_reklamy>false</show_reklamy>
		<app_image>http://knizni-manie.cz/web/photo/siteimage.png</app_image>
		<stylesheet type="text/css">http://www.knizni-manie.cz/web/style/style.css</stylesheet>
		<screen_resolution>
			<responsive>true</responsive>
			<vyska>1366</vyska>
			<sirka>768</sirka>
		</screen_resolution>
		<autor_aplikace>appGroupe</autor_aplikace>
		<kontakt_mail>manie@mail.cz</kontakt_mail>
		<zdroj_aplikace>https://www.knizni-manie.cz</zdroj_aplikace>
		<socialni_site>twitter.com/knizni-manie</socialni_site>
		<server_hosting>wedos.cz</server_hosting>
	</konfigurace>
		
	<kniha id="1" zeme_puvodu="Anglie" druh="kniha">
		<nazev_knihy lang="cs">Romeo a Julie</nazev_knihy>
		<autor pohlavi="muž">
			<jmeno>William</jmeno>
			<prijmeni>Shakespeare</prijmeni>
		</autor>
		<klicova_slova>romeo a julie, kapuleti, montekove</klicova_slova>
		<vydavatelstvi>Zlata konvice</vydavatelstvi>
		<zanr>Drama</zanr>
		<rok_vydani>1995-03-15</rok_vydani>
		<jazyk_knihy>CZ</jazyk_knihy>
		<kod_knihy>05054664</kod_knihy>
		<nor_kod ISBN="true">978-80-7432-790-2</nor_kod>
		<pocet_stran>256</pocet_stran>
		<stav_knihy>Nové</stav_knihy>
		<stav>Na skladě</stav>
		<pocet_kusu>3</pocet_kusu>
		<cena mena="Kč" cena_s_DPH="true">258</cena>
		<popis_knihy>Jaký by byl Romeo, kdyby se narodil v dnešní přetechnizované době? A co na to panensky čistá láska Julie ve světě neřestí a násilí? Mohl by jejich vztah vůbec přečkat věky, jak o tom vypráví William Shakespeare?</popis_knihy>
		<rozsireni show="true">
			<hodnoceni>5</hodnoceni>
			<pocet_recenzi>2</pocet_recenzi>
			<komentare>0</komentare>
			<zajimavosti>Romeo a Julie v moderni době</zajimavosti>
		</rozsireni>		
		<nahled_knihy nahledID="001" format="img">
			<odkaz_na_soubor>http://www.google.com/nahled/001</odkaz_na_soubor>
			<velikost>
				<vyskaNahled>100</vyskaNahled>
				<sirkaNahled>100</sirkaNahled>
			</velikost>
			<zvetseni>true</zvetseni>
			<popis>Obrázek 1</popis>
		</nahled_knihy>		
		<informace_o_zaznamu existence="true">
			<datum_pridani>2015-05-23</datum_pridani>
			<posledni_zmena>2016-06-12</posledni_zmena>
			<autor_zaznamu>Franta</autor_zaznamu>			
		</informace_o_zaznamu>
	</kniha>
	
	<kniha id="2" zeme_puvodu="Česká Republika" druh="povídka">
		<nazev_knihy lang="cs">Válka s mloky</nazev_knihy>
		<autor pohlavi="muž">
			<jmeno>Karel</jmeno>
			<prijmeni>Čapek</prijmeni>
		</autor>
		<klicova_slova>Čapek, povídka, válka s mloky</klicova_slova>
		<vydavatelstvi>Společenství neohrožených</vydavatelstvi>
		<zanr>Román</zanr>
		<rok_vydani>1999-10-24</rok_vydani>
		<jazyk_knihy>CZ</jazyk_knihy>
		<kod_knihy>79565689</kod_knihy>
		<nor_kod ISBN="true">978-80-7390-018-2</nor_kod>
		<pocet_stran>366</pocet_stran>
		<stav_knihy>Otevřené</stav_knihy>
		<stav>Na prodejně</stav>
		<pocet_kusu>1</pocet_kusu>
		<cena mena="Kč" cena_s_DPH="false">200</cena>
		<popis_knihy>Slavná antiutopická sci-fi z roku 1936 pojednává o rase inteligentních mloků, kteří se napřed nechají využívat jako levná pracovní síla, ale po čase se jejich populace přemnoží a začne lidstvo ohrožovat. </popis_knihy>
		<rozsireni show="true">
			<hodnoceni>5</hodnoceni>
			<pocet_recenzi>15</pocet_recenzi>
			<komentare>3</komentare>
			<zajimavosti>Nejslavnější román</zajimavosti>
		</rozsireni>		
		<nahled_knihy nahledID="002" format="pdf">
			<odkaz_na_soubor>http://www.google.com/nahled/002.pdf</odkaz_na_soubor>
			<velikost>
				<vyskaNahled>180</vyskaNahled>
				<sirkaNahled>200</sirkaNahled>
			</velikost>
			<zvetseni>true</zvetseni>
			<popis>Obrázek 2 mlok</popis>
		</nahled_knihy>		
		<informace_o_zaznamu existence="true">
			<datum_pridani>2016-08-12</datum_pridani>
			<posledni_zmena>2016-12-12</posledni_zmena>
			<autor_zaznamu>Petr Klapil</autor_zaznamu>			
		</informace_o_zaznamu>
	</kniha>
	
	<kniha id="3" zeme_puvodu="Francie" druh="kniha">
		<nazev_knihy lang="cs">Na západní frontě klid</nazev_knihy>
		<autor pohlavi="muž">
			<jmeno>Erich</jmeno>
			<prijmeni>Remarque</prijmeni>
		</autor>
		<klicova_slova>válka, západní fronta, </klicova_slova>
		<vydavatelstvi>Mala punčocha</vydavatelstvi>
		<zanr>Světová literatura</zanr>
		<rok_vydani>1967-11-14</rok_vydani>
		<jazyk_knihy>CZ</jazyk_knihy>
		<kod_knihy>654896512</kod_knihy>
		<nor_kod ISBN="true">28-015-67</nor_kod>
		<pocet_stran>356</pocet_stran>
		<stav_knihy>Nové</stav_knihy>
		<stav>Na prodejně</stav>
		<pocet_kusu>2</pocet_kusu>
		<cena mena="Kč" cena_s_DPH="true">320</cena>
		<popis_knihy>Popisuje krutou realitu války a hluboké odtržení od civilního života německých vojáků vracejících se z fronty. Román podrobně výstižně představuje válečnou realitu takřka s novinářskou precizitou.  </popis_knihy>
		<rozsireni show="true">
			<hodnoceni>4</hodnoceni>
			<pocet_recenzi>16</pocet_recenzi>
			<komentare>8</komentare>
			<zajimavosti>Stejnojmenný film byl natáčen koncem 70. let i v tehdejším Československu </zajimavosti>
		</rozsireni>		
		<nahled_knihy nahledID="003" format="png">
			<odkaz_na_soubor>http://www.google.com/nahled/003.png</odkaz_na_soubor>
			<velikost>
				<vyskaNahled>180</vyskaNahled>
				<sirkaNahled>200</sirkaNahled>
			</velikost>
			<zvetseni>true</zvetseni>
			<popis>Obrázek 3 most</popis>
		</nahled_knihy>		
		<informace_o_zaznamu existence="true">
			<datum_pridani>2014-08-22</datum_pridani>
			<posledni_zmena>2017-03-17</posledni_zmena>
			<autor_zaznamu>Kaňka</autor_zaznamu>			
		</informace_o_zaznamu>
	</kniha>
	
	<kniha id="4" zeme_puvodu="Anglie" druh="kniha">
		<nazev_knihy lang="cs">Pes baskervillský</nazev_knihy>
		<autor pohlavi="muž">
			<jmeno>Arthur Conan</jmeno>
			<prijmeni>Doyle</prijmeni>
		</autor>
		<klicova_slova>Sherlock Holmes, pes baskervillský </klicova_slova>
		<vydavatelstvi>Velká kniha</vydavatelstvi>
		<zanr>Světová literatura, detektivní román</zanr>
		<rok_vydani>2014-11-20</rok_vydani>
		<jazyk_knihy>CZ</jazyk_knihy>
		<kod_knihy>365789456</kod_knihy>
		<nor_kod ISBN="true">978-80-7390-142-4</nor_kod>
		<pocet_stran>226</pocet_stran>
		<stav_knihy>Použité</stav_knihy>
		<stav>Na prodejně</stav>
		<pocet_kusu>1</pocet_kusu>
		<cena mena="Kč" cena_s_DPH="true">120</cena>
		<popis_knihy>Sir Karel, pán na Baskervillském zámku, zemřel za záhadných okolností. Stála za jeho smrtí stará kletba, která podle legendy jeho rod pronásleduje již od anglické Velké revoluce? Nezdá se to rodinnému  </popis_knihy>
		<rozsireni show="true">
			<hodnoceni>4</hodnoceni>
			<pocet_recenzi>0</pocet_recenzi>
			<komentare>1</komentare>
			<zajimavosti>Stejnojmenný film byl natočen na několik způsobů </zajimavosti>
		</rozsireni>		
		<nahled_knihy nahledID="004" format="png">
			<odkaz_na_soubor>http://www.google.com/nahled/004.png</odkaz_na_soubor>
			<velikost>
				<vyskaNahled>280</vyskaNahled>
				<sirkaNahled>300</sirkaNahled>
			</velikost>
			<zvetseni>false</zvetseni>
			<popis>Obrázek 4 Wotsen</popis>
		</nahled_knihy>		
		<informace_o_zaznamu existence="true">
			<datum_pridani>2015-06-15</datum_pridani>
			<posledni_zmena>2017-03-25</posledni_zmena>
			<autor_zaznamu>Leprch</autor_zaznamu>			
		</informace_o_zaznamu>
	</kniha>
	
	<kniha id="5" zeme_puvodu="Anglie" druh="časopis">
		<nazev_knihy lang="cs">Past na myši</nazev_knihy>
		<autor pohlavi="muž">
			<jmeno>Agatha</jmeno>
			<prijmeni>Christie</prijmeni>
		</autor>
		<klicova_slova>Myška nechce do pasti, hop nebo trop </klicova_slova>
		<vydavatelstvi>Nástněnka</vydavatelstvi>
		<zanr>Světová literatura, detektivka</zanr>
		<rok_vydani>1961-02-19</rok_vydani>
		<jazyk_knihy>EN</jazyk_knihy>
		<kod_knihy>46789123</kod_knihy>
		<nor_kod ISBN="true">80-9874-632-45</nor_kod>
		<pocet_stran>128</pocet_stran>
		<stav_knihy>Nové</stav_knihy>
		<stav>Na skladě</stav>
		<pocet_kusu>10</pocet_kusu>
		<cena mena="eu" cena_s_DPH="false">50</cena>
		<popis_knihy>Děj hry se odehrává v uzavřeném prostoru Penziónu U klášterní studny, v němž se za sněhové bouře schází velmi nesourodá skupina osob, z nichž každá má své tajemství i společné vazby.</popis_knihy>
		<rozsireni show="true">
			<hodnoceni>2</hodnoceni>
			<pocet_recenzi>3</pocet_recenzi>
			<komentare>1</komentare>
			<zajimavosti>Žádné zajímavosti </zajimavosti>
		</rozsireni>		
		<nahled_knihy nahledID="005" format="jpg">
			<odkaz_na_soubor>http://www.google.com/nahled/005.jpg</odkaz_na_soubor>
			<velikost>
				<vyskaNahled>280</vyskaNahled>
				<sirkaNahled>300</sirkaNahled>
			</velikost>
			<zvetseni>false</zvetseni>
			<popis>Obrázek 5 myš</popis>
		</nahled_knihy>		
		<informace_o_zaznamu existence="true">
			<datum_pridani>2065-01-14</datum_pridani>
			<posledni_zmena>2017-02-04</posledni_zmena>
			<autor_zaznamu>Tralala</autor_zaznamu>			
		</informace_o_zaznamu>
	</kniha>
</knihovna>
